name: Release new version
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [index.js]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      #   with:
      #     node-version: latest
      - name: install dependencies
        # - uses: actions/setup-node@v4

        run: bun install --frozen-lockfile
      - name: upgrade version
        run: bun upgrade-version patch
      - name: build
        run: bun run build
      - name: get tag name
        id: get_tag_name
        run: |
          echo "{TAG_NAME}={v$(npm pkg get version)}" >> $GITHUB_ENV
      - name: commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.js package.json dist
          git commit -m "[github-actions] release $(npm pkg get version)"
          git push
# git tag -a ${{ env.TAG_NAME }} -m "Release ${{ env.TAG_NAME }}"
